
package net.webservicex;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-12T09:57:12.954-05:00
 * Generated source version: 2.4.2
 * 
 */
public final class StockQuoteSoap_StockQuoteSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.webserviceX.NET/", "StockQuote");

    private StockQuoteSoap_StockQuoteSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = StockQuote.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        StockQuote ss = new StockQuote(wsdlURL, SERVICE_NAME);
        StockQuoteSoap port = ss.getStockQuoteSoap();  
        
        {
        System.out.println("Invoking getQuote...");
        java.lang.String _getQuote_symbol = "";
        java.lang.String _getQuote__return = port.getQuote(_getQuote_symbol);
        System.out.println("getQuote.result=" + _getQuote__return);


        }

        System.exit(0);
    }

}
