package cxf.client.demo.simple;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-12-04T13:45:52.001-06:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "SimpleServiceService", 
                  wsdlLocation = "file:docs/SimpleService.wsdl",
                  targetNamespace = "http://demo.client.cxf/") 
public class SimpleServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://demo.client.cxf/", "SimpleServiceService");
    public final static QName SimpleServicePort = new QName("http://demo.client.cxf/", "SimpleServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:docs/SimpleService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SimpleServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:docs/SimpleService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SimpleServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SimpleServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SimpleServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SimpleServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SimpleServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SimpleService
     */
    @WebEndpoint(name = "SimpleServicePort")
    public SimpleService getSimpleServicePort() {
        return super.getPort(SimpleServicePort, SimpleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleService
     */
    @WebEndpoint(name = "SimpleServicePort")
    public SimpleService getSimpleServicePort(WebServiceFeature... features) {
        return super.getPort(SimpleServicePort, SimpleService.class, features);
    }

}
