package cxf.client.demo.complex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-05T10:17:46.529-06:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://demo.client.cxf/", name = "ComplexService")
@XmlSeeAlso({ObjectFactory.class})
public interface ComplexService {

    @WebMethod
    @RequestWrapper(localName = "complexMethod1", targetNamespace = "http://demo.client.cxf/", className = "cxf.client.demo.complex.ComplexMethod1")
    @ResponseWrapper(localName = "complexMethod1Response", targetNamespace = "http://demo.client.cxf/", className = "cxf.client.demo.complex.ComplexMethod1Response")
    @WebResult(name = "return", targetNamespace = "")
    public cxf.client.demo.complex.ComplexResponse complexMethod1(
        @WebParam(name = "arg0", targetNamespace = "")
        cxf.client.demo.complex.ComplexRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "complexMethod2", targetNamespace = "http://demo.client.cxf/", className = "cxf.client.demo.complex.ComplexMethod2")
    @ResponseWrapper(localName = "complexMethod2Response", targetNamespace = "http://demo.client.cxf/", className = "cxf.client.demo.complex.ComplexMethod2Response")
    @WebResult(name = "return", targetNamespace = "")
    public cxf.client.demo.complex.ComplexResponse complexMethod2(
        @WebParam(name = "arg0", targetNamespace = "")
        cxf.client.demo.complex.ComplexRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "complexMethod3", targetNamespace = "http://demo.client.cxf/", className = "cxf.client.demo.complex.ComplexMethod3")
    @ResponseWrapper(localName = "complexMethod3Response", targetNamespace = "http://demo.client.cxf/", className = "cxf.client.demo.complex.ComplexMethod3Response")
    @WebResult(name = "return", targetNamespace = "")
    public cxf.client.demo.complex.ComplexResponse complexMethod3(
        @WebParam(name = "arg0", targetNamespace = "")
        cxf.client.demo.complex.ComplexRequest arg0
    ) throws ComplexContrivedException_Exception;
}
