package cxf.client.demo.complex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-12-04T13:37:09.888-06:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "ComplexServiceService", 
                  wsdlLocation = "file:docs/ComplexService.wsdl",
                  targetNamespace = "http://demo.client.cxf/") 
public class ComplexServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://demo.client.cxf/", "ComplexServiceService");
    public final static QName ComplexServicePort = new QName("http://demo.client.cxf/", "ComplexServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:docs/ComplexService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ComplexServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:docs/ComplexService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ComplexServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ComplexServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComplexServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ComplexServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ComplexServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ComplexServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ComplexService
     */
    @WebEndpoint(name = "ComplexServicePort")
    public ComplexService getComplexServicePort() {
        return super.getPort(ComplexServicePort, ComplexService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComplexService
     */
    @WebEndpoint(name = "ComplexServicePort")
    public ComplexService getComplexServicePort(WebServiceFeature... features) {
        return super.getPort(ComplexServicePort, ComplexService.class, features);
    }

}
