package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-06T19:45:56.612-06:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET", name = "ICD9HttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ICD9HttpPost {

    /**
     * ICD-9-CM CLASSIFICATION OF DISEASES AND INJURIES by Description
     */
    @WebMethod(operationName = "GetICD9ByDescription")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getICD9ByDescription(
        @WebParam(partName = "ICDDescription", name = "ICDDescription", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String icdDescription
    );

    /**
     * ICD-9-CM CLASSIFICATION OF DISEASES AND INJURIES - Level2 
     */
    @WebMethod(operationName = "GetICD9Level2")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getICD9Level2(
        @WebParam(partName = "ICD9Level1ID", name = "ICD9Level1ID", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String icd9Level1ID
    );

    /**
     * ICD-9-CM CLASSIFICATION OF DISEASES AND INJURIES-Level 1
     */
    @WebMethod(operationName = "GetICD9Level1")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getICD9Level1();

    /**
     * ICD-9-CM CLASSIFICATION OF DISEASES AND INJURIES - Level4
     */
    @WebMethod(operationName = "GetICD9Level4")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getICD9Level4(
        @WebParam(partName = "ICDCode", name = "ICDCode", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String icdCode
    );

    /**
     * ICD-9-CM CLASSIFICATION OF DISEASES AND INJURIES - Level3 
     */
    @WebMethod(operationName = "GetICD9Level3")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public java.lang.String getICD9Level3(
        @WebParam(partName = "fromICDCode", name = "fromICDCode", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String fromICDCode,
        @WebParam(partName = "toICDCode", name = "toICDCode", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String toICDCode
    );
}
