
package cxf.client.demo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-12T09:56:58.548-05:00
 * Generated source version: 2.4.2
 * 
 */
public final class SimpleServicePortType_SimpleServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://demo.client.cxf/", "SimpleService");

    private SimpleServicePortType_SimpleServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SimpleService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SimpleService ss = new SimpleService(wsdlURL, SERVICE_NAME);
        SimpleServicePortType port = ss.getSimpleServicePort();  
        
        {
        System.out.println("Invoking simpleMethod2...");
        cxf.client.demo.SimpleRequest _simpleMethod2_request = null;
        cxf.client.demo.SimpleResponse _simpleMethod2__return = port.simpleMethod2(_simpleMethod2_request);
        System.out.println("simpleMethod2.result=" + _simpleMethod2__return);


        }
        {
        System.out.println("Invoking simpleMethod1...");
        cxf.client.demo.SimpleRequest _simpleMethod1_request = null;
        cxf.client.demo.SimpleResponse _simpleMethod1__return = port.simpleMethod1(_simpleMethod1_request);
        System.out.println("simpleMethod1.result=" + _simpleMethod1__return);


        }

        System.exit(0);
    }

}
