package cxf.client.demo.authorization;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-05T10:17:46.233-06:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "AuthorizationServiceService", 
                  wsdlLocation = "file:docs/AuthorizationService.wsdl",
                  targetNamespace = "http://demo.client.cxf/") 
public class AuthorizationServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://demo.client.cxf/", "AuthorizationServiceService");
    public final static QName AuthorizationServicePort = new QName("http://demo.client.cxf/", "AuthorizationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:docs/AuthorizationService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuthorizationServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:docs/AuthorizationService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthorizationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthorizationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthorizationServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AuthorizationServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuthorizationServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuthorizationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AuthorizationService
     */
    @WebEndpoint(name = "AuthorizationServicePort")
    public AuthorizationService getAuthorizationServicePort() {
        return super.getPort(AuthorizationServicePort, AuthorizationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthorizationService
     */
    @WebEndpoint(name = "AuthorizationServicePort")
    public AuthorizationService getAuthorizationServicePort(WebServiceFeature... features) {
        return super.getPort(AuthorizationServicePort, AuthorizationService.class, features);
    }

}
