package cxf.client.demo.secure;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-12-04T13:45:52.958-06:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "SecureServiceService", 
                  wsdlLocation = "file:docs/SecureService.wsdl",
                  targetNamespace = "http://demo.client.cxf/") 
public class SecureServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://demo.client.cxf/", "SecureServiceService");
    public final static QName SecureServicePort = new QName("http://demo.client.cxf/", "SecureServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:docs/SecureService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SecureServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:docs/SecureService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SecureServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SecureServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecureServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SecureServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SecureServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SecureServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SecureService
     */
    @WebEndpoint(name = "SecureServicePort")
    public SecureService getSecureServicePort() {
        return super.getPort(SecureServicePort, SecureService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecureService
     */
    @WebEndpoint(name = "SecureServicePort")
    public SecureService getSecureServicePort(WebServiceFeature... features) {
        return super.getPort(SecureServicePort, SecureService.class, features);
    }

}
