package cxf.client.demo.secure;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-05T11:18:06.553-06:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://demo.client.cxf/", name = "SecureService")
@XmlSeeAlso({ObjectFactory.class})
public interface SecureService {

    @WebMethod
    @RequestWrapper(localName = "secureMethod", targetNamespace = "http://demo.client.cxf/", className = "cxf.client.demo.secure.SecureMethod")
    @ResponseWrapper(localName = "secureMethodResponse", targetNamespace = "http://demo.client.cxf/", className = "cxf.client.demo.secure.SecureMethodResponse")
    @WebResult(name = "SimpleResponse", targetNamespace = "")
    public cxf.client.demo.secure.SimpleResponse secureMethod();
}
