package com.cxf.demo.sample.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-06T19:45:56.766-06:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://demo.cxf.com/", name = "SampleService")
@XmlSeeAlso({ObjectFactory.class})
public interface SampleService {

    @WebMethod
    @RequestWrapper(localName = "serviceMethod", targetNamespace = "http://demo.cxf.com/", className = "com.cxf.demo.sample.client.ServiceMethod")
    @ResponseWrapper(localName = "serviceMethodResponse", targetNamespace = "http://demo.cxf.com/", className = "com.cxf.demo.sample.client.ServiceMethodResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String serviceMethod();
}
