---
cxf:
    client:
        simpleServiceClient:
            wsdl: docs/SimpleService.wsdl
            wsdlArgs: -autoNameResolution
            clientInterface: cxf.client.demo.simple.SimpleServicePortType
            serviceEndpointAddress: http://localhost:8080/services/simple
            namespace: cxf.client.demo.simple
            httpClientPolicy: customHttpClientPolicy
        customSecureAuthorizationServiceClient:
            wsdl: docs/AuthorizationService.wsdl
            clientInterface: cxf.client.demo.authorization.AuthorizationServicePortType
            serviceEndpointAddress: http://localhost:8080/services/authorization
            namespace: cxf.client.demo.authorization
            authorizationPolicy: customAuthorizationPolicy
        simpleServiceInterceptorClient:
            wsdl: docs/SimpleService.wsdl #only used for wsdl2java script target
            clientInterface: cxf.client.demo.simple.SimpleServicePortType
            serviceEndpointAddress: http://localhost:8080/services/simple
            outInterceptors: customLoggingOutInterceptor #can use single item, comma separated list or groovy list
            inInterceptors:
              - customLoggingInInterceptor
              - verboseLoggingInInterceptor
            enableDefaultLoggingInterceptors: false
            namespace: cxf.client.demo.simple
        complexServiceClient:
            wsdl: docs/ComplexService.wsdl #only used for wsdl2java script target
            clientInterface: cxf.client.demo.complex.ComplexServicePortType
            serviceEndpointAddress: http://localhost:8080/services/complex
            namespace: cxf.client.demo.complex
            receiveTimeout: 120000 #2min
        insecureServiceClient:
            wsdl: docs/SecureService.wsdl #only used for wsdl2java script target
            namespace: cxf.client.demo.secure
            clientInterface: cxf.client.demo.secure.SecureServicePortType
            secured: false
            serviceEndpointAddress: http://localhost:8080/services/secure
        customSecureServiceClient:
            wsdl: docs/SecureService.wsdl
            namespace: cxf.client.demo.secure
            clientInterface: cxf.client.demo.secure.SecureServicePortType
            secured: true
            securityInterceptor: myCustomerSecurityOutInterceptor
            serviceEndpointAddress: http://localhost:8080/services/secure
        customSecureServiceOutClient:
            wsdl: docs/SecureService.wsdl #only used for wsdl2java script target
            namespace: cxf.client.demo.secure
            clientInterface: cxf.client.demo.secure.SecureServicePortType
            secured: true
            securityInterceptor: myCustomerSecurityOutInterceptor
            outInterceptors: customLoggingOutInterceptor #can use single item, comma separated list or groovy list
            inInterceptors:
              - customLoggingInInterceptor
              - verboseLoggingInInterceptor
            enableDefaultLoggingInterceptors: true #true by default (redundant)
            serviceEndpointAddress: http://localhost:8080/services/secure
        secureServiceClient:
            wsdl: docs/SecureService.wsdl #only used for wsdl2java script target
            namespace: cxf.client.demo.secure
            clientInterface: cxf.client.demo.secure.SecureServicePortType
            secured: true
            username: wsuser
            password: password
            serviceEndpointAddress: http://localhost:8080/services/secure
        stockQuoteClient:
            wsdl: http://www.webservicex.net/stockquote.asmx?WSDL
            clientInterface: net.webservicex.StockQuoteSoap
            serviceEndpointAddress: http://www.webservicex.net/stockquote.asmx
            receiveTimeout: 120000 #2min
            connectionTimeout: 120000 #2min

---
grails:
    profile: web
    codegen:
        defaultPackage: org.grails.cxf.client.demo
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

endpoints:
    jmx:
        unique-names: true

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
